version: "3.8"
services:
  isrdom-app:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Uncomment if you want to mount local code for development
    # volumes:
    #   - .:/app
