services:
  isr-calculator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: isr-calculator-app
    ports:
      - "4000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
